language: node_js
node_js:
- '7'
cache: npm
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: OBjviJsyeGq/1aVXMHYy+jRGxhbjqrA8RdEynng9cfct45KHgEB7wIrJee3uPJborDF+82VJhG/MhwV9raboQubmS9OkoX5b3OK2b88P66QjCy8LYG3XQNcsGeXYw0Af0KCmL1v6+ugmI5x3zZ7nDLhVHwS5W9CnEfiZ37f+sa3dWwsoLlQCY4GJpYoTqyaV6BoP/hkePmMJOzNe+0GEK+bgckSvbysLFJL/jE0En7GqKMySoIN25e6Xg7QXEUdO5RnpRQj9zTSEo3hEqIjvzQO1lK5UcEjXMni0/rt/4lwxTpA27mscn4f+R6xa36LWIklAXEvi9P1wyBc8w33OFqezql7JBTuO6q58RGDuRJea/wPp1FstsnE5KoqIxqO9NMW0X769C0Xk5+5jiEKtxaqnh1Tj/Aa0sREunh1agG9ex7w1kKmM4l8ZXe2GHQz5jZKMcJBWG2Ti7bQqN0HnViAOkqvFU4o5VJ9h0Z0QncG5nP7VqEPYp+WuqbPNWhiXZCCFmjEyzLvHC2Wtc007m78IoC7jH50oa58lhYIy/0EkV6umX7ZWBZM29KhxqS3yf6o75ph7u1Y4JvtyoBT32V6pfbMk4MFbKI719JO2w0iVwbVtX4AnRjqjhHT6Pw7mpfIsOmxhUIYe7tum/LDIG1VLLGQfQPq/T9/GHv4/5a8=
  app: ts-node-red-project-bp
