language: node_js
node_js:
- '10'
cache: npm
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: TDZIFsGllP+gJCUrWbgHmk19IqfTZuRzGQumCEzF2KFLzuEu8jykrpkWwf4P9DxaYsSDfjCJ9l4c9Er4VVE2VjCScsunUKTW/ifNPAVDmX1J/H91RURrG3mwMlm6t8KvQQCwE/RYqGrAoB/aKzIZ8brcM34MrUm17pqzS+Tay1GuuIbghLFlCGkgCQwd4rg9xmxQnrDu5wgzvraX9l+2m/Tyv9Zm9S6eV8Ky0UDp14WBdYeLtNxGppM/StV+kx/0xukE8X2MQB1hiok6Moq3Nk3GV4J1Yc+aGamHRfZCMBM1K8e+hBszx1sLWb1BUEv5DRT5k3BDfkCJewxiUfJtNZkHdByobnrrBnLmmNNpsss+mTY2HmHf7fXZyfVfkdg14iWAtjJhsOdqJXWEVAjneeJnzIzhJYmATPn8Tgg6MfW1cMeuAH4FuP7GcZvEJik2bEsGbVg/9EmZX4jCaoPDPl0djptC0HWfnWrBbeSTiyqHxkRZUOJ44e3tQxXZMpwxwk/V/HXmMIVa5NauI/UMkpNEzozHTD33h57HyY1JDUdUu6fGUp++yJSkcbCZlE7fAMIIwlthecmtyIQmClk0fn5q7A3/saGLpVboDRcpcUVlLE0jBtgA6/6C/9bCIOArZbq1AsmCyb64u9eDfutVBCFUo8Z7AS7+kkLpuN5XIhg=
  app: ts-node-red-project-bp
