language: node_js
node_js:
- '10'
cache: npm
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: E6WXYEsdtT8RbWnP8CyEYHZsDC9Zu2tMpMfQ0nrL1jKI1VTBrEn2H05yyc8tF6oibZN9sa/FCg/xOUPJD8ZOATziERybjzt2D0hnD8FDqV0fCsgkTTsTUedA1/gGDkPjVxAxQyPO8s2QJWQbYIza7sZfYnM+gpwHiwkESBPdSNIBSpeh3O7yq+yvtjXICNizchRro1lFaB2uOnzWRZPioiPumkDJTtLfmldyDGNkn74fMk60ylRbevbjEqc8v3S5uNNRszDTNEFkHOGL0LVOM7i7eYlUIyYvuDYptLMOFUVEOPbq7A1O+58jVxktVVP6CX3ZOxMyBX5UPfEXaBIXAujn2C7Bytumyf07uzY3IJAo+VgaJ0TI4aZGSZlxhV2mdYWph3IXjrC0IyHO5zXiHGsH3QJRmnitKFLjXAfK0WDVF9B8Bkm9+fV7VKL3esV6EB05771siWK8Okb+GjTX0LcIi1Xwd7HRhd63mFXshaEfQqGsjSsdkq8aHWOV6fgkKRztXQLzYCWbDkNHAmmW7FqoEpz5phM0SzISAPxzDDQQNjhwtluTw1o3H+hiVMWk3/dv8uXxIVCPDiCx5gwfCax/EQvdOuua9zMIb3QbfrJDi04Jwhwa5LQpF0oQf+ASA/ZzyaUKDxZmBMSomcizbB30abdKp+8PoYQjKyPM5Pk=
  app: ts-node-red-project-bp
