language: node_js
node_js:
- '10'
cache: npm
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: XL5tw2B2govG5cW6JyAlhuUCLCfhSr3ZlO0+ckzh6O20fcTRo9smKDq3I/2c6Zp2qGMtRQDJci1hWB6qbpo89OcDQzgw0zruPGTnIMLBmlA7EIEfTEZK9tkr0YODE6G8I9CnCCvpOqAKoh1VSvsKk+eFtNgYBIBNgnG5A//GCW9dB0JTOALwiMKA7MJrjnIt4CCK701+Oc7T2YlgqPLxtlvAJW8kTtE3t76RFY1A3NQ+7xYDn91tiFnQAPx5wv6wN1N0XWpaxGFFblQlcnVk6IKWw6jVW5tSkNUpTYD5aCkSkPeNn9ufM1Ud1G//y2pO+ldq2Cy1YeIfopyCPRxIx5eLjAAYWBi+jveWupWQQkzjVdI1TzDfUQKrb89fqu6n4C82k6WGh3nNtMVEwR50CilBcriWSsrcZablqEw54ut6nnaNMXjpWYYRBcAT1hLrMHX9oFCeQw4U10h7YVjgn39YgkGF6NqXcIsBg/xigm2cLMADqPZvafqrpnb/Vq1+TQGt3/JkthuOwu3OwUuaPx6zidnLFt5SLoSBR/pcCTIilEMHuOFoNJr4snE2uThvn5BeWYEBAc3yV8NXgmmzRzqYfAvX+s9IElMwaEPyZUUkGEJxCGbvPkeHsf2RRkZHJuSNEwg/Zo7Jy+VJuSdkOa2KMxOenSeNfArxhQPe7Ic=
  app: ts-node-red-project-bp
