language: node_js
node_js:
- '7'
cache: npm
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: F/L30rmgCbbnA9Q+7ttkykEIcRZ9EiR2wD4XytxxuKdjy77be1nj+Q4NzbpmnPrdbvsBgrcV4qMfuK7ce4pgO8UyQXUX2MaJq6Guzk+7+eW4lUemmQzzT2dICIhIo4vqbMe2/MftAP9vK7jR03h0VstyJD2Q9GLzQoCXimufvu2M3a9YoFX9cXL054iiSm0/5nn2q0AiU+igCInNdOOOsb8Z0A9p0FXYY5wNY2n+rlA0CP5wW1EyEw3EVGCPnUGoOphPXy08SD6rVwVH9qjgJ+RJf3Z8zhUtNribNNFlb6kNBluDQ1kmgFSlXxAvog+GLpY0AuYPADEYnrqC3GKuaU3iT2jBARNg1RUNHBCR1XK7o8VYYBWhsK/n5qwGMwXwjmD8+D9SLKvv8b/wLUoT0bkMJ1w7jY8QRwkFmN4aI24aY5rq6D/vGoxe3bd0dFLYbtozG7YgML0AXN548cvfh237Wjlqjg+AAqoPytzBA/BJJ9qWFTtULtPvoLO/U43waZeNbrhEJwvx/C558OqUYLr5KUni8EyM6ENplayCi0ldwo++helBHW0lqAs+tUmoBLFQqas8VlGPVaz78raFGmEqMroFG7NlD1zeNzq1MXy5HhP7ls1qZrsrvqyyM5j0mWhrF5bIDaAGqObJTQXKAZ18tcaunmkcV6f4n0C04pg=
  app: node-red-sample-app
  on:
    repo: bishoymelek/node-red-sample-app
